import Head from "next/head";
import Nextui from "../components/nextui/nextprovider";
import "./globals.css";
// redux
import { Providers } from "../components/Redux/provider";
import { ThemeContextProvider } from "../components/context/store";

export const metadata = {
  title: "Rayan Post",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#f4f3f3]">
      <Head>
        <link
          rel="icon"
          type="image/x-icon"
          href="/favicon.ico"
          sizes="16x16"
        />
      </Head>
      <body>
    <Nextui>
        <ThemeContextProvider>
          <Providers>{children}</Providers>
        </ThemeContextProvider>

    </Nextui>
    
      </body>
    </html>
  );
}
