import Head from "next/head";
import "./globals.css";

export const metadata = {
  title: "Rayan Post",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="icon"
          type="image/x-icon"
          href="/favicon.ico"
          sizes="16x16"
        />
      </Head>
      <body>{children}</body>
    </html>
  );
}
